#!/usr/bin/env bash

##############################################
#   Author: RMCJ <rmichael1001@gmail.com>
#   Project: com.github.rmj1001.Post-Installers
#   Version: 1.0
#
#   Usage: postinstall
#
#   Description:
#		Curlable Postinstallation Script
##############################################

function PRINT() { printf "%b\n" "${@}"; }
function LOWERCASE() {
    printf "%b" "${1}" | tr "[:upper:]" "[:lower:]"
}

clear

PRINT "
 ######                         ###                                             #     #                                    
 #     #  ####   ####  #####     #  #    #  ####  #####   ##   #      #         #     # ###### #      #####  ###### #####  
 #     # #    # #        #       #  ##   # #        #    #  #  #      #         #     # #      #      #    # #      #    # 
 ######  #    #  ####    #       #  # #  #  ####    #   #    # #      #         ####### #####  #      #    # #####  #    # 
 #       #    #      #   #       #  #  # #      #   #   ###### #      #         #     # #      #      #####  #      #####  
 #       #    # #    #   #       #  #   ## #    #   #   #    # #      #         #     # #      #      #      #      #   #  
 #        ####   ####    #      ### #    #  ####    #   #    # ###### ######    #     # ###### ###### #      ###### #    # 
"

PRINT
PRINT "Choose a Distro/App (number):"
PRINT "1. Fedora"
PRINT "2. Ubuntu"
PRINT ""
PRINT "90. Flatpaks"
PRINT "91. Homebrew"
PRINT "92. Papirus Icons"
PRINT "93. Zap (AppImage manager)"
PRINT
PRINT "0. Exit"
PRINT
read -r -p "# > " scriptNumber

case "$(LOWERCASE "${scriptNumber}")" in
1 | fedora)
    wget -qO- "https://raw.githubusercontent.com/rmj1001/Post-Installers/main/distros/fedora.sh" | bash
    ;;

2 | ubuntu)
    wget -qO- "https://raw.githubusercontent.com/rmj1001/Post-Installers/main/distros/ubuntu.sh" | bash
    ;;

90 | flatpaks)
    wget -qO- "https://raw.githubusercontent.com/rmj1001/Post-Installers/main/misc/flatconfig.sh" | bash
    ;;

91 | homebrew)
    wget -qO- "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh" | bash
    ;;

92 | 'papirus icons')
    wget -qO- "https://git.io/papirus-icon-theme-install" | sh
    wget -qO- "https://git.io/papirus-folders-install" | sh

    papirus-folders --theme Papirus-Dark -C yaru
    papirus-folders --theme Papirus-Light -C yaru
    ;;

93 | zap)
    # Zap Appimage PM (requires jq)
    [[ -x "$(command -v jq)" ]] || {
        PRINT "postinstall: 'jq' must be installed to install Zap."
        exit 1
    }

    bash -c "$(wget -qO- "https://raw.githubusercontent.com/srevinsaju/zap/main/install.sh")"

    ;;

0 | exit)
    PRINT "Exiting."
    PRINT
    exit 0
    ;;
esac
