#!/usr/bin/env bash

##############################################
#   Author: RMCJ <rmichael1001@gmail.com>
#   Project: com.github.rmj1001.Post-Installers
#   Version: 1.0
#
#   Usage: postinstall
#
#   Description:
#		Curlable Postinstallation Script
##############################################

function PRINT() { printf "%b\n" "${@}"; }
function LOWERCASE() {
    printf "%b" "${1}" | tr "[:upper:]" "[:lower:]"
}
function FINDCMD() {
    [[ -x "$(command -v ${1})" ]] && return 0
    return 1
}

INSTALLERS_DISTROS="https://raw.githubusercontent.com/rmj1001/Post-Installers/main/distros"
INSTALLERS_MISC="https://raw.githubusercontent.com/rmj1001/Post-Installers/main/misc"

clear

PRINT "
 ######                         ###                                             #     #                                    
 #     #  ####   ####  #####     #  #    #  ####  #####   ##   #      #         #     # ###### #      #####  ###### #####  
 #     # #    # #        #       #  ##   # #        #    #  #  #      #         #     # #      #      #    # #      #    # 
 ######  #    #  ####    #       #  # #  #  ####    #   #    # #      #         ####### #####  #      #    # #####  #    # 
 #       #    #      #   #       #  #  # #      #   #   ###### #      #         #     # #      #      #####  #      #####  
 #       #    # #    #   #       #  #   ## #    #   #   #    # #      #         #     # #      #      #      #      #   #  
 #        ####   ####    #      ### #    #  ####    #   #    # ###### ######    #     # ###### ###### #      ###### #    # 
"

PRINT
PRINT "Choose a Distro/App (number):"
PRINT "1. Fedora"
PRINT "2. Ubuntu"
PRINT ""
PRINT "90. Flatpaks"
PRINT "91. Homebrew"
PRINT "92. Papirus Icons"
PRINT "93. Zap (AppImage manager)"
PRINT "94. Doas (sudo alternative)"
PRINT
PRINT "0. Exit"
PRINT
read -r -p "# > " scriptNumber

clear

case "$(LOWERCASE "${scriptNumber}")" in
1 | fedora)
    wget -qO- "${INSTALLERS_DISTROS}/fedora.sh" | bash
    ;;

2 | ubuntu)
    wget -qO- "${INSTALLERS_DISTROS}/ubuntu.sh" | bash
    ;;

90 | flatpaks)
    wget -qO- "${INSTALLERS_MISC}/flatconfig.sh" | bash
    ;;

91 | homebrew)
    wget -qO- "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh" | bash
    ;;

92 | 'papirus icons')
    wget -qO- "https://git.io/papirus-icon-theme-install" | sh
    wget -qO- "https://git.io/papirus-folders-install" | sh

    papirus-folders --theme Papirus-Dark -C yaru
    papirus-folders --theme Papirus-Light -C yaru
    ;;

93 | zap)
    # Zap Appimage PM (requires jq)
    FINDCMD "jq" || {
        PRINT "postinstall: 'jq' must be installed to install Zap."
        exit 1
    }

    bash -c "$(wget -qO- "https://raw.githubusercontent.com/srevinsaju/zap/main/install.sh")"
    ;;

94 | doas)
    FINDCMD "dnf" || FINDCMD "apt" || FINDCMD "zypper" || {
        PRINT "postinstall: 'doas' not supported for your distro."
        exit 1
    }

    FINDCMD "dnf" &&
        sudo dnf install gcc gcc-c++ make flex bison pam-devel byacc

    FINDCMD "apt" &&
        sudo apt install build-essential make bison flex libpam0g-dev

    FINDCMD "zypper" &&
        sudo zypper install gcc gcc-c++ make flex bison pam-devel byacc git

    mkdir ~/.local/share/com.github.rmj1001.Post-Installers.git-repos
    cd ~/.local/share/com.github.rmj1001.Post-Installers.git-repos

    git clone https://github.com/slicer69/doas.git
    cd ./doas

    make
    sudo make install
    sudo cp /etc/pam.d/sudo /etc/pam.d/doas
    PRINT "Doas installed! Run 'sudo vidoas' to edit the config file."
    PRINT "Make sure to type 'permit $USER as root'."
    ;;

0 | exit)
    PRINT "Exiting."
    PRINT
    exit 0
    ;;
esac
