#!/usr/bin/env bash

##############################################
#   Author: RMCJ <rmichael1001@gmail.com>
#   Project: com.github.rmj1001.Post-Installers
#   Version: 1.0
#
#   Usage: postinstall
#
#   Description:
#		Curlable Postinstallation Script
##############################################

function PRINT() { printf "%b\n" "${@}"; }
function LOWERCASE() {
    printf "%b" "${1}" | tr "[:upper:]" "[:lower:]"
}

clear

PRINT "Post Installation Helper"
PRINT
PRINT "Choose a Distro/App (number):"
PRINT "1. Fedora"
PRINT "2. Ubuntu"
PRINT ""
PRINT "90. Flatpaks"
PRINT "91. Homebrew"
PRINT "92. Papirus Icons"
PRINT "93. Zap (AppImage manager)"
PRINT
PRINT "0. Exit"
PRINT
read -r -p "# > " scriptNumber

case "$(LOWERCASE "${scriptNumber}")" in
1 | fedora)
    wget -qO- \
        "https://raw.githubusercontent.com/rmj1001/Post-Installers/main/distros/fedora.sh" |
        bash -c
    ;;

2 | ubuntu)
    wget -qO- \
        "https://raw.githubusercontent.com/rmj1001/Post-Installers/main/distros/ubuntu.sh" |
        bash -c
    ;;

90 | flatpaks)
    wget -qO- \
        "https://raw.githubusercontent.com/rmj1001/Post-Installers/main/misc/flatconfig.sh" |
        bash -c
    ;;

91 | homebrew)
    wget -qO- \
        "https://raw.githubusercontent.com/rmj1001/Post-Installers/main/misc/homebrew.sh" |
        bash -c
    ;;

92 | 'papirus icons')
    wget -qO- \
        "https://raw.githubusercontent.com/rmj1001/Post-Installers/main/misc/papirus-icons.sh" |
        bash -c
    ;;

93 | zap)
    wget -qO- \
        "https://raw.githubusercontent.com/rmj1001/Post-Installers/main/misc/zap.sh" |
        bash -c
    ;;

0 | exit)
    PRINT "Exiting."
    PRINT
    exit 0
    ;;
esac
